name: EnderKits
description: A chest kit plugin.
main: ChestKits\Main
version: 1.0.0
api: [5.0.0]

commands:
  kit:
    description: "server kits"
    permission: enderkit.cmd
    
permissions:
  enderkits.cmd:
    description: "Enderkits Perm"
    default: true
